spring:
  application:
    name: essentials
  datasource:
    url: jdbc:mysql://localhost:3306/gym?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: ${JWT_EXPIRATION:900000} # 15 minutos
  key: ${JWT_KEY:3EuBbjZGV1iexOqGl1BDtM2BjrRV6lZDHc8VXIiD9ds=}